sudo: false
language: node_js
node_js:
    - "4.2.6"

addons:
  firefox: "latest"

branches:
    only:
        - master
        - dev

install:
    - npm install

cache:
    directories:
        - node_modules

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm run build

script:
    - karma start --browsers Firefox --reporters=dots,coverage,coveralls  --single-run
